version: '3.8'
services:
  neo4j:
    image: neo4j:5.20
    container_name: neo4j-tp
    ports:
      - "7474:7474"   # interfaz web
      - "7687:7687"   # puerto de conexi√≥n para VS Code
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
    volumes:
      - ./data:/data
      - ./import:/import
